/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C"
{
#endif

	struct operandos
	{
		int a;
		int b;
	};
	typedef struct operandos operandos;

	int suma(operandos *operandos) { return operandos->a + operandos->b; }

#endif /* !_CALCULADORA_H_RPCGEN */
