/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <time.h>

int main(int argc, char *argv[])
{
	char *host;

	//Comprobamos que se haya llamado al programa correctamente.

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	//Solicitamos al usuario que operación desea realizar:

	int operando1, operando2;

	system("clear");
	printf("Este programa mide el tiempo que tarda en realizarse una llamada a una función sumar local 100.000 veces\n");
	printf("Introduzca el operando 1: ");
	scanf("%d", &operando1);

	while (abs(operando1) - 10 > 0)
	{
		printf("Error, los operandos deben ser números de 1 cifra.\n");
		printf("Introduzca el operando 1: ");
		scanf("%d", &operando1);
	}

	printf("Introduzca el operando 2: ");
	scanf("%d", &operando2);

	while (abs(operando2) - 10 > 0)
	{
		printf("Error, los operandos deben ser números de 1 cifra.\n");
		printf("Introduzca el operando 2: ");
		scanf("%d", &operando2);
	}

	CLIENT *clnt;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	int *result;
	int total = 0;
	operandos operandos = {operando1, operando2};

	clock_t begin = clock();

	for (int i = 0; i < 100000; i++)
	{

		result = suma_1(&operandos, clnt);
		if (result == (int *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		total += *result;
	}

	clock_t end = clock();
	double time_spent = (double)(end - begin) / CLOCKS_PER_SEC;

	printf("El resultado de la suma es: %d\n", total);
	printf("Ha tardado: %f segundos\n", time_spent);

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
	exit(0);
}
